name: Release
on:
  workflow_dispatch:
    inputs:
      scope:
        description: "Reckon scope"
        required: true
      stage:
        description: "Reckon stage"
        required: true
jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8, 11, 15]
      fail-fast: false
    steps:
      - name: "Checkout repo"
        uses: "actions/checkout@v2"
        with:
          fetch-depth: 0
      - name: "Fetch all tags"
        run: "git fetch origin +refs/tags/*:refs/tags/*"
      - name: "Setup Java ${{ matrix.java }}"
        uses: "actions/setup-java@v1"
        with:
          java-version: ${{ matrix.java }}
      - name: "Cache Gradle wrapper"
        uses: "actions/cache@v1"
        with:
          path: "~/.gradle/wrapper"
          key: "gradle-wrapper-${{ runner.os }}-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}"
      - name: "Cache Gradle welcome message"
        uses: "actions/cache@v1"
        with:
          path: "~/.gradle/notifications"
          key: "gradle-notifications-${{ runner.os }}-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}"
      - name: "Cache Gradle dependencies"
        uses: "actions/cache@v1"
        with:
          path: "~/.gradle/caches"
          key: "gradle-caches-${{ runner.os }}-${{ hashFiles('**/gradle/dependency-locks/*.lockfile') }}"
      - name: "Gradle check"
        run: "./gradlew check --continue  -Preckon.scope=${{ github.event.inputs.scope }} -Preckon.stage=${{ github.event.inputs.stage }}"
  publish:
    runs-on: ubuntu-latest
    needs: check
    environment: release
    steps:
      - name: "Checkout repo"
        uses: "actions/checkout@v2"
        with:
          fetch-depth: 0
      - name: "Fetch all tags"
        run: "git fetch origin +refs/tags/*:refs/tags/*"
      - name: "Setup Java"
        uses: "actions/setup-java@v1"
        with:
          java-version: 8
      - name: "Cache Gradle wrapper"
        uses: "actions/cache@v1"
        with:
          path: "~/.gradle/wrapper"
          key: "gradle-wrapper-${{ runner.os }}-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}"
      - name: "Cache Gradle welcome message"
        uses: "actions/cache@v1"
        with:
          path: "~/.gradle/notifications"
          key: "gradle-notifications-${{ runner.os }}-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}"
      - name: "Cache Gradle dependencies"
        uses: "actions/cache@v1"
        with:
          path: "~/.gradle/caches"
          key: "gradle-caches-${{ runner.os }}-${{ hashFiles('**/gradle/dependency-locks/*.lockfile') }}"
      - name: "Gradle publish"
        env:
          CLOJARS_USER: ${{ secrets.CLOJARS_USER }}
          CLOJARS_TOKEN: ${{ secrets.CLOJARS_TOKEN }}
          GRADLE_OPTS: "-Dorg.gradle.project.gradle.publish.key=${{ secrets.GRADLE_PLUGIN_KEY }} -Dorg.gradle.project.gradle.publish.secret=${{ secrets.GRADLE_PLUGIN_SECRET }}"
        run: "./gradlew reckonTagPush publish publishPlugins -Preckon.scope=${{ github.event.inputs.scope }} -Preckon.stage=${{ github.event.inputs.stage }}"
